Add MVP version of the library
Wikia/AlphaB pull request #1
Opened 2019-11-24 09:45 UTC by veliona

## Goal of the PR

## How to test it

## Additional information

2019-11-26 12:28 UTC, Ullaakut requested changes

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +        custom_interval=1
This option should have a more explicit name 🤔 

WDYT of `custom_day_interval`? And what happens if the `x_axis` isn't a date?

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +* ```df``` - assigns previously grouped data frame to this argument; this can include specification of a certain value within a column in the data frame (exp. `df[df['device' == 'mobile']]`)
It's not clear here what is a `previously grouped data frame`. WDYT of

```suggestion
* `df` - data frame to be used for the bucket test. It is recommended to group the data frame before passing it (e.g.: When doing a bucket test on the group `design`, you should group the data frame by design and date first)
```

Also, triple back ticks should be used for multi-line code blocks, while single back ticks are for in-line code blocks, which should be the case here :)

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +* ```y_axis``` - specifies the values on the y_axis for the chart and statistical significance check
Actually, what do you think of renaming this `y_axis` to `variable`? From what I've seen, in A/B testing, what we called the `y_axis` here is usually called the variable 🤔 But I might be wrong!

```suggestion
* `y_axis` - the name of the column to use on the Y axis of the chart and statistical significance check.
```

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +* ```group``` - assigns a column in the data frame which contains groups for A/B testing
WDYT of

```suggestion
* `group` - the name of the column which the data frame is grouped by
```

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +* ```x_axis``` (default: `date`) - specifies the values on the x_axis for the chart
```suggestion
* `x_axis` (default: `date`) - the name of the column to use on the X axis of the chart
```

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +* ```custom_title``` (default: `y_axis`) - specifies the title for the chart
The default value for custom title isn't `y_axis`, it's `{y_axis} per {group}`

```suggestion
* `custom_title` (default: `{y_axis} per {group}`) - a custom title for the chart
```

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +
Unnecessary newline

```suggestion
```

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +* Group data frame so that it can be given to `bucket_test.render()`
What do you mean by that?

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +* Render charts and compute p-values for data from more than one data frame
Shouldn't that be done by doing multiple bucket tests? It sounds to me like one bucket test should do one rendering and one computing of pvalues, if there are multiple tests to handle, they should be in separate tests, otherwise the library would become overcomplicated and it definitely shouldn't :)

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +You can contribute by creating a new branch on the repository and a PR
I'd suggest something maybe a little less vague than this :p WDYT of

```suggestion
You can contribute by forking this repository, looking through the [issues](https://github.com/Wikia/AlphaB/issues) of the repository, and opening a PR on your fork. Please make sure to write a clear PR description and to provide examples for how your new feature works.
```

Maybe something like that?

2019-11-26 12:28 UTC, Ullaakut commented on README.md
> +Thank a lot!
```suggestion
Thanks a lot!
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +    def render(self, figure_size_x=12, figure_size_y=5, line_width=3, title_font_size=16, legend_font_size=14):
WDYT of also documenting the arguments/options for the `render` method in the README? Maybe with less details than creating a BucketTest, but still, it could be nice to show that it's customizable :)

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +        # Title customization statement
```suggestion
        # Title customization
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +            plt.ylabel('')
By default, the column name used for the y_axis should probably be the label name, rather than nothing

```suggestion
            plt.ylabel(self.y_axis)
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +        plt.xticks(rotation=30);
```suggestion
        plt.xticks(rotation=30)
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +        plt.savefig(Path("Chart"));
```suggestion
        plt.savefig(Path("Chart"))
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +        # Major locator customization statement
```suggestion
        # Major locator customization
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +        if self.custom_interval != 1:
This `if/else` statement is unnecessary

```suggestion
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +            ax.xaxis.set_major_locator(mdates.DayLocator(interval=self.custom_interval))
```suggestion
        ax.xaxis.set_major_locator(mdates.DayLocator(interval=self.custom_interval))
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +        else:
```suggestion
```

2019-11-26 12:28 UTC, Ullaakut commented on bucket_test.py
> +            ax.xaxis.set_major_locator(mdates.DayLocator(interval=1))
```suggestion
```

2019-11-26 12:28 UTC, Ullaakut commented on example/.ipynb_checkpoints/example-checkpoint.ipynb
> +{
This file should not be added to the repository.

2019-11-26 12:28 UTC, Ullaakut commented on main.py
> +#!/usr/bin/env python3
Maybe we can rename this file to `example.py` to make it clear that AlphaB is a library and this file is just an example of how it can be used? Actually maybe this file can even go away completely, now that the example is in the README and the Jupyter Notebook?

2019-11-26 12:28 UTC, Ullaakut commented on requirements.txt
> +
What are those 3 newlines at the end of the file?

2019-11-26 12:28 UTC, Ullaakut commented on .gitignore
> +.idea/*
I'd suggest adding the following rules:

`.DS_Store` to avoid adding MacOS config files
`example/.ipynb_checkpoints` to avoid adding jupyter notebook cache data

2019-11-26 12:43 UTC, Ullaakut requested changes

2019-11-26 12:43 UTC, Ullaakut commented on example/example.ipynb
> +    "This notebook is created to showcase the data analysis possibilities using [AlphaB library](https://github.com/Wikia/AlphaB) as well as compare results and the code using traditional way of anal
```suggestion
    "This notebook showcases the data analysis possibilities of the [AlphaB library](https://github.com/Wikia/AlphaB) and compares it to a manual approach.\n",
```

2019-11-26 12:43 UTC, Ullaakut commented on example/example.ipynb
> +    "# AlphaB code\n",
This shouldn't be here, it should just be an import of the installed AlphaB library

2019-11-26 23:36 UTC, veliona reviewed
Thanks a lot!!! I applied the changes :)

2019-11-26 23:36 UTC, veliona commented on .gitignore
> +.idea/*
Thanks! This was changed! :)

2019-11-26 23:36 UTC, veliona commented on README.md
> +* ```df``` - assigns previously grouped data frame to this argument; this can include specification of a certain value within a column in the data frame (exp. `df[df['device' == 'mobile']]`)
Changed, thank you!

2019-11-26 23:36 UTC, veliona commented on README.md
> +        custom_interval=1
Thank you! I will change `custom_interval` with `custom_day_interval`.
Currently, I would like to focus on the shipping of this and for most cases - the x-axis would be a date in A/B testings in general. Will keep it in mind and will add this to `Next steps` in the README.md.

2019-11-26 23:36 UTC, veliona commented on README.md
> +* Group data frame so that it can be given to `bucket_test.render()`
As discussed, I will remove it, since this shouldn't be in the scope of the library. Thank you for giving me tips on this type of stuff! :)

2019-11-26 23:36 UTC, veliona commented on README.md
> +* Render charts and compute p-values for data from more than one data frame
Sure, will consider that! Thanks!

2019-11-26 23:36 UTC, veliona commented on bucket_test.py
> +    def render(self, figure_size_x=12, figure_size_y=5, line_width=3, title_font_size=16, legend_font_size=14):
Yes, I was thinking about it! Thank you for reminding me. :)

2019-11-26 23:36 UTC, veliona commented on main.py
> +#!/usr/bin/env python3
I would rather keep it still as a `example.py` :)
Thank you monsieur!

2019-11-26 23:36 UTC, veliona commented on requirements.txt
> +
Will delete! Thank you! 👍

2019-11-26 23:36 UTC, veliona commented on example/example.ipynb
> +    "# AlphaB code\n",
Thanks!

2019-11-26 23:57 UTC, veliona commented on alphab/alphab.py
> +        plt.ylim(0, )
```suggestion
        plt.ylim(0)
```

2019-11-28 09:38 UTC, Ullaakut requested changes
Another `.DS_Store` file was added in the last commit. Not sure how, considering the `.gitignore` should prevent it 🤔

2019-11-29 08:43 UTC, bckatarzyna reviewed
You probably committed `example/.DS_Store` by an accident

2019-11-29 08:43 UTC, bckatarzyna commented on .gitignore
> +example/.ipynb_checkpoints
No blank line at the end of the file

2019-11-29 08:43 UTC, bckatarzyna commented on alphab/alphab.py
> +import matplotlib.pyplot as plt
Please read about [imports order](https://www.python.org/dev/peps/pep-0008/#imports)

2019-11-29 08:43 UTC, bckatarzyna commented on alphab/alphab.py
> +    def __init__(self, df: pd.DataFrame, variable: str, group: str, x_axis='date', custom_title="", custom_day_interval=1,
Think about limiting maximum line length

2019-11-29 08:43 UTC, bckatarzyna commented on alphab/alphab.py
> +    def render(self, figure_size_x=12, figure_size_y=5, line_width=3, title_font_size=16, legend_font_size=14):
You can think about creating a separate config file for such default values to make it easier to edit by user

2019-11-29 08:43 UTC, bckatarzyna commented on alphab/alphab.py
> +    def __init__(self, df: pd.DataFrame, variable: str, group: str, x_axis='date', custom_title="", custom_day_interval=1,
And don't mix `''` with `""`

2019-11-29 08:43 UTC, bckatarzyna commented on alphab/alphab.py
> +            plt.ylabel(self.variable)
```suggestion
            plt.ylabel(self.custom_ylabel or self.variable)
```
^ Should work and it's shorter

2019-11-29 08:43 UTC, bckatarzyna commented on alphab/alphab.py
> +        if normality_pvalue_a > 0.01 and normality_pvalue_b > 0.01:
Do we always want to have it on 0.01 level? Maybe it could also be configurable?

2019-11-29 09:04 UTC, Ullaakut commented on alphab/alphab.py
> +    def render(self, figure_size_x=12, figure_size_y=5, line_width=3, title_font_size=16, legend_font_size=14):
This is a library, so I'm not sure what you mean by config file? A file in the library in which there are constants for each default value? If so, users won't be editing it unless they fork the library 😕 

IMO, being able to see what the defaults are directly by looking at the method's prototype is more user-friendly than having to look in a separate file, especially since nowadays modern IDEs show you the prototype by just holding command and hovering over the method's name:

<img width="849" alt="Screenshot 2019-11-29 at 10 02 32 AM" src="https://user-images.githubusercontent.com/6976628/69857085-6574d400-128f-11ea-9069-d88288ac70c5.png">

I think that if the default values are exported to a file, at least some IDEs won't be able to resolve the default values and they will no longer be shown.

WDYT? 🙂

2019-11-29 10:52 UTC, veliona reviewed
Thank you @bckatarzyna for your review! 👍

2019-11-29 10:52 UTC, veliona commented on .gitignore
> +example/.ipynb_checkpoints
Thank you, will take more care with this! :)

2019-11-29 10:52 UTC, veliona commented on alphab/alphab.py
> +    def __init__(self, df: pd.DataFrame, variable: str, group: str, x_axis='date', custom_title="", custom_day_interval=1,
I actually did it, PyCharm was showing me where I should move my code into a new line - that's why `custom_ylabel` is in a new line. PyCharm was not correct with that? I should move `custom_day_interval` into a new line as well?

2019-11-29 10:52 UTC, veliona commented on alphab/alphab.py
> +    def render(self, figure_size_x=12, figure_size_y=5, line_width=3, title_font_size=16, legend_font_size=14):
Thank you @bckatarzyna and @Ullaakut ! :)

2019-11-29 10:52 UTC, veliona commented on alphab/alphab.py
> +        if normality_pvalue_a > 0.01 and normality_pvalue_b > 0.01:
Sure, as far as I know, 0.05 and 0.01 are the most common values. For some experiments, the lower value might be more appropriate and for the other 0.05.
That's a good idea to make it configurable! Thanks! 👍

2019-11-29 13:06 UTC, bckatarzyna commented on alphab/alphab.py
> +    def render(self, figure_size_x=12, figure_size_y=5, line_width=3, title_font_size=16, legend_font_size=14):
That's true, I only imagined a situation when somebody uses this function a lot and always wants to have different values than those given here - then it would save a lot of copy-pasting.
But @Ullaakut arguments are right, it's better to have them as they are.

2019-11-29 13:44 UTC, veliona commented on alphab/alphab.py
> +    def __init__(self, df: pd.DataFrame, variable: str, group: str, x_axis='date', custom_title="", custom_day_interval=1,
For now, I will leave it as PyCharm recommends me - 120 lines, might change that in the future though, thanks!

2019-12-02 08:44 UTC, veliona reviewed
I will keep in mind your comment on this @Ullaakut. Thanks! :)

2019-12-02 09:38 UTC, Ullaakut commented on README.md
> +In the `compute_pvalues()` method, you can customize the p-value used to reject a null hypothesis by adjusting `alpha` value (default: 0.01).
```suggestion
In the `compute_pvalues()` method, you can customize the p-value used to reject a null hypothesis by adjusting the `alpha` value (default: `0.01`).
```

2019-12-02 09:38 UTC, Ullaakut commented on README.md
> +Recommended values are: 0.01, 0.05, 0.1.
```suggestion
Recommended values are: `0.01`, `0.05`, `0.1`.
```

2019-12-02 09:38 UTC, Ullaakut commented on README.md
> +I also, recommend [this research paper](http://www.scielo.br/pdf/bpsr/v7n1/02.pdf) for those who wants better understand those topics.
```suggestion
[This research paper](http://www.scielo.br/pdf/bpsr/v7n1/02.pdf) is also a good place to start for those who want to better understand those topics.
```

2019-12-09 16:08 UTC, Loczi94 approved these changes
Looks good. 👍 I left few comments.

2019-12-09 16:08 UTC, Loczi94 commented on README.md
> +<!-- <p align="center"><img src="images/AlphaB.png" width="250"/></p> -->
Is it some kind of placeholder for a logo or you forgot to remove it?

2019-12-09 16:08 UTC, Loczi94 commented on README.md
> +* The method for checking statistical significance was highly inspired by the work of **Paulina Gralak [@Loczi94](https://github.com/Loczi94)**.
❤️

2019-12-09 16:08 UTC, Loczi94 commented on alphab/alphab.py
> +        plt.xticks(rotation=30)
I think that it could be configurable since `ratation=30` may not look good in same cases. So maybe it could be another parameter of `render` function with default value `30`.

2019-12-09 16:08 UTC, Loczi94 commented on alphab/alphab.py
> +        normality_group_b, normality_pvalue_b = shapiro(group_b)
`normality_group_a ` and `normality_group_b ` are not used anywhere so you can replace it by:
`normality_pvalue_a = shapiro(group_a)[1]`
`normality_pvalue_b = shapiro(group_b)[1]`
It's up to you. Maybe your solutions is more readable.

2019-12-09 16:08 UTC, Loczi94 commented on alphab/alphab.py
> +                print('T-test p-value: ', welch_pvalue)
It's Welch's test not T-test. (:

2019-12-09 16:14 UTC, veliona commented on alphab/alphab.py
> +        normality_group_b, normality_pvalue_b = shapiro(group_b)
I think I put readability on top of the cleanest of code. Let's leave it like this. :)

2019-12-09 16:23 UTC, veliona commented on alphab/alphab.py
> +        plt.xticks(rotation=30)
Sure, good idea! Thanks! 👍

2020-02-06 15:08 UTC, merged